name: Fetch posts

on:
  push:
    branches:
      - main
  schedule:
    - cron:  "32 9,18,22 * * *"

jobs:
  fetch_posts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: run
        run: ruby run.rb

      - name: Commit and push changes
        uses: devops-infra/action-commit-push@master
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          commit_message: "Auto: add rss-feed updates"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output

